name: Cron for Veek check-in

on:
  schedule:
    - cron: '13 13 * * *'
  workflow_dispatch:

jobs:
  check-in:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: First check-in
        run: node index.js
        env:
          VEEK_LINES: ${{ secrets.VEEK_LINES }}

      - name: Wait one minute
        run: sleep 60

      - name: Second check-in
        run: node index.js
        env:
          VEEK_LINES: ${{ secrets.VEEK_LINES }}
